### ISSUE TITLE
import multimetric and use it

### ISSUE THREAD

**Issue by lStiven** [priv-kweihmann/multimetric#25]
Hi, I have a question, could I import multimetric in a python class? and use it programmatically?
Right now, I'm using it with subprocess import

```
import subprocess
import json


info = subprocess.run(["multimetric", "example.py"], capture_output=True)
info_to_json = json.loads(info.stdout.decode("utf-8"))
```

**Comment by priv-kweihmann** [comment]
Hi, currently that not supported, but I think I could implement that easily if that is needed

**Comment by priv-kweihmann** [comment]
I close this one for now - fell free to open an enhancement for importing the tool, if you still think that is needed

**Comment by priv-kweihmann** [comment]
FYI: Part of release 2.0.0
