### ISSUE TITLE
Which Programming Languages

### ISSUE THREAD

**Issue by firas-jolha** [priv-kweihmann/multimetric#29]
Hi,

I would like to ask about which programming languages does your tool support. I think it is good to add this info to the documentation. 

Thanks!

**Comment by priv-kweihmann** [comment]
Hi,

that is actually a pretty good idea and I would love to see if the new maintainer (see #21) will add that (I also accept PRs to add it).
The tool itself can tokenize every language that is supported by [pygments](https://pygments.org/languages/) - fine tuning has only been done for c/c++, js, php, go, ruby and python

**Comment by priv-kweihmann** [comment]
Part of release 2.0.0
